[package]
name = "zudp"
version = "0.2.0"
edition = "2018"
authors = ["Alexander Zelenyak <zzz.sochi@gmail.com>"]
description = "Simple tool for receive UDP datagrams."
repository = "https://github.com/zzzsochi/zudp"
categories = ["command-line-interface"]

[dependencies]
clap = "3.0.0-beta.2"
